% cellTypeClassificationFR

close all

% IC all cells
meanPVic = mean(log(fr.mouse.all(list.mouse.PV)));
meanSSTic = mean(log(fr.mouse.all(list.mouse.SST)));
meanVIPic = mean(log(fr.mouse.all(list.mouse.VIP)));
meanPyric = mean(log(fr.mouse.all(list.mouse.Pyr)));
figure('Position',[50 50 250 200]); set(gcf,'color','w');
    hold on
    histogram(log(fr.mouse.all(list.mouse.Pyr)),edges.FR.IC,...
        'FaceColor','k','Normalization','probability','EdgeColor','none');
    histogram(log(fr.mouse.all(list.mouse.PV)),edges.FR.IC,...
        'FaceColor','r','Normalization','probability','EdgeColor','none');
    histogram(log(fr.mouse.all(list.mouse.SST)),edges.FR.IC,...
        'FaceColor','g','Normalization','probability','EdgeColor','none');
    histogram(log(fr.mouse.all(list.mouse.VIP)),edges.FR.IC,...
        'FaceColor','b','Normalization','probability','EdgeColor','none');
    line([meanPVic,meanPVic],[0,0.3],...
        'color','r','linewidth',1,'linestyle','--');
    line([meanSSTic,meanSSTic],[0,0.3],...
        'color','g','linewidth',1,'linestyle','--');
    line([meanVIPic,meanVIPic],[0,0.3],...
        'color','b','linewidth',1,'linestyle','--');
    line([meanPyric,meanPyric],[0,0.3],...
        'color','k','linewidth',1,'linestyle','--');
    histogram(log(fr.mouse.all),edges.FR.IC,'FaceColor',...
        [0.85 0.85 0.85],'Normalization','probability','EdgeColor','none');
    plot(inflection.mouse.fr.x,inflection.mouse.fr.yfun1,'k','LineWidth',1);
    plot(inflection.mouse.fr.x,inflection.mouse.fr.yfun2,'k','LineWidth',1);
    line([inflection.mouse.fr.peakLocs,inflection.mouse.fr.peakLocs],...
        [0,0.3],'color','k','linewidth',1,'linestyle','--');
    ylabel('probability')
    xlabel('firing rate (Hz)')
    axis tight
    xlim([edges.FR.IC(1) edges.FR.IC(end)])

% EC all cells & cell types
meanPVec = mean(log(fr.mouseVivo.all(list.mouseVivo.PV)));
meanSSTec = mean(log(fr.mouseVivo.all(list.mouseVivo.SST)));
meanVIPec = mean(log(fr.mouseVivo.all(list.mouseVivo.VIP)));
meanPyrec = mean(log(fr.mouseVivo.all(list.mouseVivo.broad)));
    figure('Position',[50 50 250 200]); set(gcf,'color','w');
    hold on
    histogram(log(fr.mouseVivo.all(list.mouseVivo.broad)),edges.FR.EC,...
        'FaceColor','k','Normalization','probability','EdgeColor','none');
    histogram(log(fr.mouseVivo.all(list.mouseVivo.PV)),edges.FR.EC,...
        'FaceColor','r','Normalization','probability','EdgeColor','none');
    histogram(log(fr.mouseVivo.all(list.mouseVivo.SST)),edges.FR.EC,...
        'FaceColor','g','Normalization','probability','EdgeColor','none');
    histogram(log(fr.mouseVivo.all(list.mouseVivo.VIP)),edges.FR.EC,...
        'FaceColor','b','Normalization','probability','EdgeColor','none');
    line([meanPVec,meanPVec],[0,0.25],...
        'color','r','linewidth',1,'linestyle','--');
    line([meanSSTec,meanSSTec],[0,0.25],...
        'color','g','linewidth',1,'linestyle','--');
    line([meanVIPec,meanVIPec],[0,0.25],...
        'color','b','linewidth',1,'linestyle','--');
    line([meanPyrec,meanPyrec],[0,0.25],...
        'color','k','linewidth',1,'linestyle','--');
    histogram(log(fr.mouseVivo.all),edges.FR.EC,...
        'FaceColor',[0.85 0.85 0.85],'Normalization','probability','EdgeColor','none');
    plot(inflection.mouseVivo.fr.x,inflection.mouseVivo.fr.yfun1,'k','LineWidth',1);
    plot(inflection.mouseVivo.fr.x,inflection.mouseVivo.fr.yfun2,'k','LineWidth',1);
    line([inflection.mouseVivo.fr.peakLocs,inflection.mouseVivo.fr.peakLocs],...
        [0,0.16],'color','k','linewidth',1,'linestyle','--');
    ylabel('probability')
    xlabel('firing rate (Hz)')
    axis tight
    xlim([edges.FR.EC(1) edges.FR.EC(end)])

close all
clear fitresult gof h wfCenters wfCounts wfFitCurveS 

% distance scores for IC
dist.fr.PV2PV = abs(meanPVic-log(fr.mouse.all(list.mouse.PV)));
dist.fr.PV2SST = abs(meanPVic-log(fr.mouse.all(list.mouse.SST)));
dist.fr.PV2VIP = abs(meanPVic-log(fr.mouse.all(list.mouse.VIP)));
dist.fr.PV2Pyr = abs(meanPVic-log(fr.mouse.all(list.mouse.Pyr)));
dist.fr.SST2PV = abs(meanSSTic-log(fr.mouse.all(list.mouse.PV)));
dist.fr.SST2SST = abs(meanSSTic-log(fr.mouse.all(list.mouse.SST)));
dist.fr.SST2VIP = abs(meanSSTic-log(fr.mouse.all(list.mouse.VIP)));
dist.fr.SST2Pyr = abs(meanSSTic-log(fr.mouse.all(list.mouse.Pyr)));
dist.fr.VIP2PV = abs(meanVIPic-log(fr.mouse.all(list.mouse.PV)));
dist.fr.VIP2SST = abs(meanVIPic-log(fr.mouse.all(list.mouse.SST)));
dist.fr.VIP2VIP = abs(meanVIPic-log(fr.mouse.all(list.mouse.VIP)));
dist.fr.VIP2Pyr = abs(meanVIPic-log(fr.mouse.all(list.mouse.Pyr)));
dist.fr.Pyr2PV = abs(meanPyric-log(fr.mouse.all(list.mouse.PV)));
dist.fr.Pyr2SST = abs(meanPyric-log(fr.mouse.all(list.mouse.SST)));
dist.fr.Pyr2VIP = abs(meanPyric-log(fr.mouse.all(list.mouse.VIP)));
dist.fr.Pyr2Pyr = abs(meanPyric-log(fr.mouse.all(list.mouse.Pyr)));

% distance classification
for i = 1:length(dist.fr.PV2PV)
    vec = [dist.fr.PV2PV(i),dist.fr.SST2PV(i),dist.fr.VIP2PV(i),...
        dist.fr.Pyr2PV(i)];
    [~,loc] = min(vec);
    pred.fr.PV(i) = loc;
end
for i = 1:length(dist.fr.PV2SST)
    vec = [dist.fr.PV2SST(i),dist.fr.SST2SST(i),dist.fr.VIP2SST(i),...
        dist.fr.Pyr2SST(i)];
    [~,loc] = min(vec);
    pred.fr.SST(i) = loc;
end
for i = 1:length(dist.fr.PV2VIP)
    vec = [dist.fr.PV2VIP(i),dist.fr.SST2VIP(i),dist.fr.VIP2VIP(i),...
        dist.fr.Pyr2VIP(i)];
    [~,loc] = min(vec);
    pred.fr.VIP(i) = loc;
end
for i = 1:length(dist.fr.Pyr2Pyr)
    vec = [dist.fr.PV2Pyr(i),dist.fr.SST2Pyr(i),dist.fr.VIP2Pyr(i),...
        dist.fr.Pyr2Pyr(i)];
    [~,loc] = min(vec);
    pred.fr.Pyr(i) = loc;
end
figure('Position',[50 50 200 200]); set(gcf,'color','w');
    mat = [sum(pred.fr.PV==1)/length(pred.fr.PV),...
        sum(pred.fr.SST==1)/length(pred.fr.SST),...
        sum(pred.fr.VIP==1)/length(pred.fr.VIP),...
        sum(pred.fr.Pyr==1)/length(pred.fr.Pyr);...
        sum(pred.fr.PV==2)/length(pred.fr.PV),...
        sum(pred.fr.SST==2)/length(pred.fr.SST),...
        sum(pred.fr.VIP==2)/length(pred.fr.VIP),...
        sum(pred.fr.Pyr==2)/length(pred.fr.Pyr);...
        sum(pred.fr.PV==3)/length(pred.fr.PV),...
        sum(pred.fr.SST==3)/length(pred.fr.SST),...
        sum(pred.fr.VIP==3)/length(pred.fr.VIP),...
        sum(pred.fr.Pyr==3)/length(pred.fr.Pyr);...
        sum(pred.fr.PV==4)/length(pred.fr.PV),...
        sum(pred.fr.SST==4)/length(pred.fr.SST),...
        sum(pred.fr.VIP==4)/length(pred.fr.VIP),...
        sum(pred.fr.Pyr==4)/length(pred.fr.Pyr)];
    imagesc(mat);
    colormap('gray')
    h = colorbar;
    ylabel(h, 'proportion')
    clear h
    xlabel('ground truth')
    ylabel('prediction')
    xticks(1:4)
    xticklabels({'PV+','SST+','VIP+','Pyr'})
    yticks(1:4)
    yticklabels({'PV+','SST+','VIP+','Pyr'})
    axis equal
    axis tight
    box off
    dim = [.21 .74 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.PV==1)),...
        'FitBoxToText','on','LineStyle','none','color','k');
    dim = [.34 .74 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.SST==1)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.46 .74 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.VIP==1)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.59 .74 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.Pyr==1)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.24 .64 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.PV==2)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.34 .64 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.SST==2)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.46 .64 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.VIP==2)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.57 .64 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.Pyr==2)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.24 .52 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.PV==3)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.34 .52 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.SST==3)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.46 .52 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.VIP==3)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.57 .52 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.Pyr==3)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.24 .41 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.PV==4)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.35 .41 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.SST==4)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.48 .41 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.VIP==4)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.57 .41 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.fr.Pyr==4)),...
        'FitBoxToText','on','LineStyle','none','color','k');
    % export_fig('Fig 7M','-pdf','-r600');
    clear h dim

% EC distance scores
dist.frVivo.PV2PV = abs(meanPVec-log(fr.mouseVivo.all(...
    list.mouseVivo.PV)));
dist.frVivo.SST2PV = abs(meanSSTec-log(fr.mouseVivo.all(...
    list.mouseVivo.PV)));
dist.frVivo.VIP2PV = abs(meanVIPec-log(fr.mouseVivo.all(...
    list.mouseVivo.PV)));
dist.frVivo.Pyr2PV = abs(meanPyrec-log(fr.mouseVivo.all(...
    list.mouseVivo.PV)));
dist.frVivo.PV2SST = abs(meanPVec-log(fr.mouseVivo.all(...
    list.mouseVivo.SST)));
dist.frVivo.SST2SST = abs(meanSSTec-log(fr.mouseVivo.all(...
    list.mouseVivo.SST)));
dist.frVivo.VIP2SST = abs(meanVIPec-log(fr.mouseVivo.all(...
    list.mouseVivo.SST)));
dist.frVivo.Pyr2SST = abs(meanPyrec-log(fr.mouseVivo.all(...
    list.mouseVivo.SST)));
dist.frVivo.PV2VIP = abs(meanPVec-log(fr.mouseVivo.all(...
    list.mouseVivo.VIP)));
dist.frVivo.SST2VIP = abs(meanSSTec-log(fr.mouseVivo.all(...
    list.mouseVivo.VIP)));
dist.frVivo.VIP2VIP = abs(meanVIPec-log(fr.mouseVivo.all(...
    list.mouseVivo.VIP)));
dist.frVivo.Pyr2VIP = abs(meanPyrec-log(fr.mouseVivo.all(...
    list.mouseVivo.VIP)));
dist.frVivo.PV2Pyr = abs(meanPVec-log(fr.mouseVivo.all(...
    list.mouseVivo.broad)));
dist.frVivo.SST2Pyr = abs(meanSSTec-log(fr.mouseVivo.all(...
    list.mouseVivo.broad)));
dist.frVivo.VIP2Pyr = abs(meanVIPec-log(fr.mouseVivo.all(...
    list.mouseVivo.broad)));
dist.frVivo.Pyr2Pyr = abs(meanPyrec-log(fr.mouseVivo.all(...
    list.mouseVivo.broad)));

% distance classification for EC cells
for i = 1:length(dist.frVivo.PV2PV)
    vec = [dist.frVivo.PV2PV(i),dist.frVivo.SST2PV(i),dist.frVivo.VIP2PV(i),...
        dist.frVivo.Pyr2PV(i)];
    [~,loc] = min(vec);
    pred.frVivo.PV(i) = loc;
end
for i = 1:length(dist.frVivo.PV2SST)
    vec = [dist.frVivo.PV2SST(i),dist.frVivo.SST2SST(i),dist.frVivo.VIP2SST(i),...
        dist.frVivo.Pyr2SST(i)];
    [~,loc] = min(vec);
    pred.frVivo.SST(i) = loc;
end
for i = 1:length(dist.frVivo.PV2VIP)
    vec = [dist.frVivo.PV2VIP(i),dist.frVivo.SST2VIP(i),dist.frVivo.VIP2VIP(i),...
        dist.frVivo.Pyr2VIP(i)];
    [~,loc] = min(vec);
    pred.frVivo.VIP(i) = loc;
end
for i = 1:length(dist.frVivo.PV2Pyr)
    vec = [dist.frVivo.PV2Pyr(i),dist.frVivo.SST2Pyr(i),dist.frVivo.VIP2Pyr(i),...
        dist.frVivo.Pyr2Pyr(i)];
    [~,loc] = min(vec);
    pred.frVivo.broad(i) = loc;
end

figure('Position',[50 50 200 200]); set(gcf,'color','w');
    mat = [sum(pred.frVivo.PV==1)/length(pred.frVivo.PV),...
        sum(pred.frVivo.SST==1)/length(pred.frVivo.SST),...
        sum(pred.frVivo.VIP==1)/length(pred.frVivo.VIP),...
        sum(pred.frVivo.broad==1)/length(pred.frVivo.broad);...
        sum(pred.frVivo.PV==2)/length(pred.frVivo.PV),...
        sum(pred.frVivo.SST==2)/length(pred.frVivo.SST),...
        sum(pred.frVivo.VIP==2)/length(pred.frVivo.VIP),...
        sum(pred.frVivo.broad==2)/length(pred.frVivo.broad);...
        sum(pred.frVivo.PV==3)/length(pred.frVivo.PV),...
        sum(pred.frVivo.SST==3)/length(pred.frVivo.SST),...
        sum(pred.frVivo.VIP==3)/length(pred.frVivo.VIP),...
        sum(pred.frVivo.broad==3)/length(pred.frVivo.broad);...
        sum(pred.frVivo.PV==4)/length(pred.frVivo.PV),...
        sum(pred.frVivo.SST==4)/length(pred.frVivo.SST),...
        sum(pred.frVivo.VIP==4)/length(pred.frVivo.VIP),...
        sum(pred.frVivo.broad==4)/length(pred.frVivo.broad)];
    imagesc(mat);
    colormap('gray')
    h = colorbar;
    ylabel(h, 'proportion')
    clear h
    xlabel('ground truth')
    ylabel('prediction')
    xticks(1:4)
    xticklabels({'PV+','SST+','VIP+','broad'})
    yticks(1:4)
    yticklabels({'PV+','SST+','VIP+','broad'})
    axis equal
    axis tight
    box off
    dim = [.21 .74 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.PV==1)),...
        'FitBoxToText','on','LineStyle','none','color','k');
    dim = [.34 .74 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.SST==1)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.46 .74 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.VIP==1)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.59 .74 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.broad==1)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.24 .64 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.PV==2)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.34 .64 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.SST==2)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.46 .64 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.VIP==2)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.57 .64 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.broad==2)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.24 .52 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.PV==3)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.34 .52 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.SST==3)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.46 .52 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.VIP==3)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.57 .52 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.broad==3)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.24 .41 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.PV==4)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.35 .41 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.SST==4)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.48 .41 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.VIP==4)),...
        'FitBoxToText','on','LineStyle','none','color','w');
    dim = [.57 .41 0 0];
    annotation('textbox',dim,'String',int2str(sum(pred.frVivo.broad==4)),...
        'FitBoxToText','on','LineStyle','none','color','k');
    % export_fig('Fig 7M','-pdf','-r600');
    clear h dim
    
close all
clear i loc n mat meanPVec meanPVic meanPyrec meanPyric meanSSTec ...
    meanSSTic meanVIPic vec