%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\neuropixels\units.csv
%
% Auto-generated by MATLAB on 09-Mar-2020 10:53:50

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 27);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["id", "PT_ratio", "amplitude", "amplitude_cutoff", "cumulative_drift", "d_prime", "duration", "ecephys_channel_id", "epoch_name_quality_metrics", "epoch_name_waveform_metrics", "firing_rate", "halfwidth", "isi_violations", "isolation_distance", "l_ratio", "max_drift", "nn_hit_rate", "nn_miss_rate", "presence_ratio", "quality", "recovery_slope", "repolarization_slope", "silhouette_score", "snr1", "spread", "velocity_above", "velocity_below"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["epoch_name_quality_metrics", "epoch_name_waveform_metrics", "quality"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("MMneuropixelUnits.csv", opts);

%% Convert to output type
unit.id = tbl.id;
unit.PT_ratio = tbl.PT_ratio;
unit.amplitude = tbl.amplitude;
unit.amplitude_cutoff = tbl.amplitude_cutoff;
unit.cumulative_drift = tbl.cumulative_drift;
unit.d_prime = tbl.d_prime;
unit.duration = tbl.duration;
unit.ecephys_channel_id = tbl.ecephys_channel_id;
unit.epoch_name_quality_metrics = tbl.epoch_name_quality_metrics;
unit.epoch_name_waveform_metrics = tbl.epoch_name_waveform_metrics;
unit.firing_rate = tbl.firing_rate;
unit.halfwidth = tbl.halfwidth;
unit.isi_violations = tbl.isi_violations;
unit.isolation_distance = tbl.isolation_distance;
unit.l_ratio = tbl.l_ratio;
unit.max_drift = tbl.max_drift;
unit.nn_hit_rate = tbl.nn_hit_rate;
unit.nn_miss_rate = tbl.nn_miss_rate;
unit.presence_ratio = tbl.presence_ratio;
unit.quality = tbl.quality;
unit.recovery_slope = tbl.recovery_slope;
unit.repolarization_slope = tbl.repolarization_slope;
unit.silhouette_score = tbl.silhouette_score;
unit.snr1 = tbl.snr1;
unit.spread = tbl.spread;
unit.velocity_above = tbl.velocity_above;
unit.velocity_below = tbl.velocity_below;

%% Clear temporary variables
clear opts tbl